// Generated from docs/TAXONOMY_V2.md and the English mapping; slugs are English (stable ids), names carry pt-PT and en.
namespace Savvori.WebApi.Scraping;

public record V2Aisle(string Slug, string NamePt, string NameEn, IReadOnlyList<V2Leaf> Leaves);
public record V2Leaf(string Slug, string NamePt, string NameEn);

/// <summary>The approved taxonomy v2: 12 aisles and their leaf categories (see docs/TAXONOMY_V2.md). Slugs are English.</summary>
public static class TaxonomyV2Data
{
    public static IReadOnlyList<V2Aisle> Aisles { get; } =
    [
        new("produce", "Frutas e Legumes", "Fruit & Vegetables",
        [
            new("fruit", "Frutas", "Fruit"),
            new("vegetables", "Legumes e Hortícolas", "Vegetables"),
            new("salads-herbs", "Saladas e Ervas Aromáticas", "Salads & Herbs"),
        ]),
        new("meat-fish", "Talho e Peixaria", "Meat & Fish",
        [
            new("beef", "Carne de Vaca", "Beef"),
            new("pork", "Carne de Porco", "Pork"),
            new("poultry", "Aves", "Poultry"),
            new("minced-prepared-meat", "Carne Picada e Preparados", "Minced & Prepared Meat"),
            new("fresh-fish", "Peixe Fresco", "Fresh Fish"),
            new("seafood", "Marisco", "Seafood"),
            new("salt-cod-cured-fish", "Bacalhau e Salgados", "Salt Cod & Cured Fish"),
        ]),
        new("deli-cheese", "Charcutaria e Queijos", "Deli & Cheese",
        [
            new("ham-cold-cuts", "Fiambre e Presunto", "Ham & Cold Cuts"),
            new("cured-sausages", "Enchidos", "Cured Sausages"),
            new("pates-cooked-deli", "Patés e Charcutaria Cozida", "Pâtés & Cooked Deli"),
            new("cheese", "Queijos", "Cheese"),
        ]),
        new("dairy-eggs", "Laticínios e Ovos", "Dairy & Eggs",
        [
            new("milk", "Leite", "Milk"),
            new("plant-drinks", "Bebidas Vegetais", "Plant-Based Drinks"),
            new("yoghurt", "Iogurtes", "Yoghurt"),
            new("dairy-desserts", "Sobremesas Lácteas", "Dairy Desserts"),
            new("butter-margarine", "Manteiga e Margarinas", "Butter & Margarine"),
            new("cooking-cream", "Natas e Cremes Culinários", "Cooking Cream"),
            new("eggs", "Ovos", "Eggs"),
        ]),
        new("bakery", "Padaria e Pastelaria", "Bakery & Pastry",
        [
            new("bread", "Pão", "Bread"),
            new("packaged-bread", "Pão de Forma e Embalado", "Sliced & Packaged Bread"),
            new("cakes-pastries", "Bolos e Pastelaria", "Cakes & Pastries"),
            new("prepared-desserts", "Sobremesas Preparadas", "Prepared Desserts"),
        ]),
        new("pantry", "Mercearia", "Pantry",
        [
            new("rice", "Arroz", "Rice"),
            new("pasta", "Massas", "Pasta"),
            new("pulses-grains", "Leguminosas e Grãos", "Pulses & Grains"),
            new("flour-baking", "Farinhas e Preparados", "Flour & Baking"),
            new("canned-fish", "Conservas de Peixe", "Canned Fish"),
            new("canned-vegetables-fruit", "Conservas Vegetais e de Fruta", "Canned Vegetables & Fruit"),
            new("sauces-seasonings", "Molhos e Temperos", "Sauces & Seasonings"),
            new("oil-vinegar", "Azeite, Óleos e Vinagres", "Olive Oil, Oils & Vinegar"),
            new("soups-ready-meals", "Sopas e Pratos Preparados", "Soups & Ready Meals"),
        ]),
        new("sweets-coffee-snacks", "Doces, Café e Snacks", "Sweets, Coffee & Snacks",
        [
            new("cereals", "Cereais e Granola", "Cereals & Granola"),
            new("plain-biscuits", "Bolachas Maria e Simples", "Plain Biscuits"),
            new("filled-biscuits", "Bolachas Recheadas e Wafers", "Filled Biscuits & Wafers"),
            new("wholegrain-biscuits", "Bolachas Integrais e de Cereais", "Wholegrain & Cereal Biscuits"),
            new("crackers", "Bolachas Salgadas e Tostas", "Crackers & Savoury Biscuits"),
            new("chocolate", "Chocolate", "Chocolate"),
            new("confectionery", "Confeitaria e Doces", "Confectionery & Sweets"),
            new("jams-honey-spreads", "Compotas, Mel e Cremes de Barrar", "Jams, Honey & Spreads"),
            new("sugar-sweeteners", "Açúcar e Adoçantes", "Sugar & Sweeteners"),
            new("coffee", "Café", "Coffee"),
            new("tea-infusions", "Chá e Infusões", "Tea & Infusions"),
            new("savoury-snacks", "Snacks Salgados", "Savoury Snacks"),
            new("nuts-seeds", "Frutos Secos e Sementes", "Nuts & Seeds"),
        ]),
        new("drinks", "Bebidas", "Drinks",
        [
            new("water", "Água", "Water"),
            new("soft-drinks", "Refrigerantes", "Soft Drinks"),
            new("juices", "Sumos e Néctares", "Juices & Nectars"),
            new("energy-sports-drinks", "Bebidas Energéticas e Desportivas", "Energy & Sports Drinks"),
            new("beer-cider", "Cerveja e Sidra", "Beer & Cider"),
            new("wine", "Vinho", "Wine"),
            new("spirits-liqueurs", "Espirituosas e Licores", "Spirits & Liqueurs"),
            new("cocktails-mixed", "Cocktails e Bebidas Mistas", "Cocktails & Mixed Drinks"),
        ]),
        new("frozen", "Congelados", "Frozen",
        [
            new("frozen-vegetables", "Legumes Congelados", "Frozen Vegetables"),
            new("frozen-fish-seafood", "Peixe e Marisco Congelados", "Frozen Fish & Seafood"),
            new("frozen-meat-poultry", "Carne e Aves Congeladas", "Frozen Meat & Poultry"),
            new("frozen-ready-meals", "Refeições Prontas Congeladas", "Frozen Ready Meals"),
            new("pizzas-savouries", "Pizzas e Salgados", "Pizzas & Savouries"),
            new("potatoes-fries", "Batatas e Pré-Fritos", "Potatoes & Fries"),
            new("ice-cream", "Gelados", "Ice Cream"),
        ]),
        new("personal-care", "Higiene e Beleza", "Personal Care & Beauty",
        [
            new("bath-body", "Banho e Higiene Pessoal", "Bath & Body"),
            new("deodorants", "Desodorizantes", "Deodorants"),
            new("oral-care", "Higiene Oral", "Oral Care"),
            new("hair-care", "Cabelo", "Hair Care"),
            new("skincare-cosmetics", "Cosmética, Rosto e Corpo", "Skincare & Cosmetics"),
            new("sun-care", "Proteção Solar", "Sun Care"),
            new("intimate-care", "Higiene Íntima e Feminina", "Intimate & Feminine Care"),
            new("shaving-hair-removal", "Barbear e Depilação", "Shaving & Hair Removal"),
            new("toilet-paper-tissues", "Papel Higiénico e Lenços", "Toilet Paper & Tissues"),
        ]),
        new("home-cleaning", "Casa e Limpeza", "Home & Cleaning",
        [
            new("laundry", "Detergentes de Roupa", "Laundry"),
            new("dishwashing", "Detergentes de Loiça", "Dishwashing"),
            new("household-cleaning", "Limpeza do Lar", "Household Cleaning"),
            new("paper-disposables", "Papel e Descartáveis", "Paper & Disposables"),
            new("air-fresheners-insecticides", "Ambientadores e Inseticidas", "Air Fresheners & Insecticides"),
            new("kitchen-dining", "Cozinha e Mesa", "Kitchen & Dining"),
            new("stationery-books", "Papelaria e Livros", "Stationery & Books"),
            new("general-seasonal", "Bazar e Sazonais", "General & Seasonal"),
        ]),
        new("baby-pets-health", "Bebé, Animais e Saúde", "Baby, Pets & Health",
        [
            new("baby-food", "Alimentação Bebé", "Baby Food"),
            new("nappies-baby-care", "Fraldas e Higiene Bebé", "Nappies & Baby Care"),
            new("baby-gear-furniture", "Puericultura e Mobiliário Bebé", "Baby Gear & Furniture"),
            new("dog-food", "Comida para Cães", "Dog Food"),
            new("cat-food", "Comida para Gatos", "Cat Food"),
            new("pet-supplies", "Outros Animais e Acessórios", "Other Pets & Supplies"),
            new("supplements-wellness", "Suplementos e Bem-Estar", "Supplements & Wellness"),
            new("pharmacy-first-aid", "Farmácia e Primeiros Socorros", "Pharmacy & First Aid"),
        ]),
    ];
}
