// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Savvori.WebApi;

#nullable disable

namespace Savvori.WebApi.Migrations
{
    [DbContext(typeof(SavvoriDbContext))]
    [Migration("20260921075331_AddMatchDecisions")]
    partial class AddMatchDecisions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Savvori.Shared.MatchCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BrandCheck")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cosine")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JudgeModel")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JudgeVerdict")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelDigest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SizeKnown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StoreProductAId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StoreProductBId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Suggestion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cosine");

                    b.HasIndex("Status");

                    b.HasIndex("StoreProductBId");

                    b.HasIndex("StoreProductAId", "StoreProductBId")
                        .IsUnique();

                    b.ToTable("MatchCandidates");
                });

            modelBuilder.Entity("Savvori.Shared.MatchMerge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovedListItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovedStoreProductsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RetiredProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetiredProductJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SurvivorPreviousCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SurvivorProductId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UndoneAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("MatchMerges");
                });

            modelBuilder.Entity("Savvori.Shared.ModelJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.HasIndex("Type", "SubjectId", "PayloadHash")
                        .IsUnique()
                        .HasDatabaseName("ix_model_jobs_active_unique")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.ToTable("ModelJobs");
                });

            modelBuilder.Entity("Savvori.Shared.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SizeValue")
                        .HasColumnType("REAL");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EAN");

                    b.HasIndex("NormalizedName");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Savvori.Shared.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Savvori.Shared.ScrapingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductsScraped")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StoreChainId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoreChainId");

                    b.ToTable("ScrapingJobs");
                });

            modelBuilder.Entity("Savvori.Shared.ScrapingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScrapingJobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScrapingJobId");

                    b.ToTable("ScrapingLogs");
                });

            modelBuilder.Entity("Savvori.Shared.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("Savvori.Shared.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("Savvori.Shared.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StoreChainId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoreChainId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Savvori.Shared.StoreCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastScraped")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentStoreCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StoreChainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentStoreCategoryId");

                    b.HasIndex("StoreChainId", "ExternalId")
                        .IsUnique();

                    b.ToTable("StoreCategories");
                });

            modelBuilder.Entity("Savvori.Shared.StoreCategoryMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StoreCategoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("StoreCategoryId")
                        .IsUnique();

                    b.ToTable("StoreCategoryMappings");
                });

            modelBuilder.Entity("Savvori.Shared.StoreChain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("StoreChains");
                });

            modelBuilder.Entity("Savvori.Shared.StoreProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CanonicalProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScraped")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchMethod")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SizeValue")
                        .HasColumnType("REAL");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StoreCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StoreChainId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EAN");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("StoreCategoryId");

                    b.HasIndex("CanonicalProductId", "IsActive");

                    b.HasIndex("StoreChainId", "ExternalId")
                        .IsUnique();

                    b.ToTable("StoreProducts");
                });

            modelBuilder.Entity("Savvori.Shared.StoreProductEmbedding", b =>
                {
                    b.Property<Guid>("StoreProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dimension")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EmbeddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputTextHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelDigest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Vector")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("StoreProductId");

                    b.HasIndex("EmbeddedAt");

                    b.ToTable("StoreProductEmbeddings");
                });

            modelBuilder.Entity("Savvori.Shared.StoreProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("EUR");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPromotion")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("PromotionDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StoreProductId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StoreProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_store_product_prices_latest")
                        .HasFilter("\"IsLatest\" = 1");

                    b.HasIndex("StoreProductId", "IsLatest");

                    b.HasIndex("StoreProductId", "ScrapedAt");

                    b.ToTable("StoreProductPrices");
                });

            modelBuilder.Entity("Savvori.Shared.MatchCandidate", b =>
                {
                    b.HasOne("Savvori.Shared.StoreProduct", "StoreProductA")
                        .WithMany()
                        .HasForeignKey("StoreProductAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Savvori.Shared.StoreProduct", "StoreProductB")
                        .WithMany()
                        .HasForeignKey("StoreProductBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreProductA");

                    b.Navigation("StoreProductB");
                });

            modelBuilder.Entity("Savvori.Shared.Product", b =>
                {
                    b.HasOne("Savvori.Shared.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Savvori.Shared.ProductCategory", b =>
                {
                    b.HasOne("Savvori.Shared.ProductCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Savvori.Shared.ScrapingJob", b =>
                {
                    b.HasOne("Savvori.Shared.StoreChain", "StoreChain")
                        .WithMany("ScrapingJobs")
                        .HasForeignKey("StoreChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreChain");
                });

            modelBuilder.Entity("Savvori.Shared.ScrapingLog", b =>
                {
                    b.HasOne("Savvori.Shared.ScrapingJob", "ScrapingJob")
                        .WithMany("Logs")
                        .HasForeignKey("ScrapingJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapingJob");
                });

            modelBuilder.Entity("Savvori.Shared.ShoppingListItem", b =>
                {
                    b.HasOne("Savvori.Shared.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Savvori.Shared.ShoppingList", null)
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Savvori.Shared.Store", b =>
                {
                    b.HasOne("Savvori.Shared.StoreChain", "StoreChain")
                        .WithMany("Locations")
                        .HasForeignKey("StoreChainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StoreChain");
                });

            modelBuilder.Entity("Savvori.Shared.StoreCategory", b =>
                {
                    b.HasOne("Savvori.Shared.StoreCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentStoreCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Savvori.Shared.StoreChain", "StoreChain")
                        .WithMany("StoreCategories")
                        .HasForeignKey("StoreChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("StoreChain");
                });

            modelBuilder.Entity("Savvori.Shared.StoreCategoryMapping", b =>
                {
                    b.HasOne("Savvori.Shared.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Savvori.Shared.StoreCategory", "StoreCategory")
                        .WithOne("Mapping")
                        .HasForeignKey("Savvori.Shared.StoreCategoryMapping", "StoreCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("StoreCategory");
                });

            modelBuilder.Entity("Savvori.Shared.StoreProduct", b =>
                {
                    b.HasOne("Savvori.Shared.Product", "CanonicalProduct")
                        .WithMany("StoreProducts")
                        .HasForeignKey("CanonicalProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Savvori.Shared.StoreCategory", "StoreCategory")
                        .WithMany("StoreProducts")
                        .HasForeignKey("StoreCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Savvori.Shared.StoreChain", "StoreChain")
                        .WithMany("StoreProducts")
                        .HasForeignKey("StoreChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalProduct");

                    b.Navigation("StoreCategory");

                    b.Navigation("StoreChain");
                });

            modelBuilder.Entity("Savvori.Shared.StoreProductEmbedding", b =>
                {
                    b.HasOne("Savvori.Shared.StoreProduct", "StoreProduct")
                        .WithOne()
                        .HasForeignKey("Savvori.Shared.StoreProductEmbedding", "StoreProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreProduct");
                });

            modelBuilder.Entity("Savvori.Shared.StoreProductPrice", b =>
                {
                    b.HasOne("Savvori.Shared.StoreProduct", "StoreProduct")
                        .WithMany("Prices")
                        .HasForeignKey("StoreProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreProduct");
                });

            modelBuilder.Entity("Savvori.Shared.Product", b =>
                {
                    b.Navigation("StoreProducts");
                });

            modelBuilder.Entity("Savvori.Shared.ProductCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Savvori.Shared.ScrapingJob", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Savvori.Shared.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Savvori.Shared.StoreCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Mapping");

                    b.Navigation("StoreProducts");
                });

            modelBuilder.Entity("Savvori.Shared.StoreChain", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("ScrapingJobs");

                    b.Navigation("StoreCategories");

                    b.Navigation("StoreProducts");
                });

            modelBuilder.Entity("Savvori.Shared.StoreProduct", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
